### ISSUE TITLE
US09 - Eu, enquanto usuário, desejo modificar meus ficheiros afim de atualiza-los

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#10]
## Descrição da Issue
Desenvolvimento da funcionalidade de edição de ficheiros.

### Tasks: 

- [x]  Criar tela de edição de ficheiro;
- [x]  Criar lógica de edição de ficheiro;
- [x]  Conectar front com back;

### Critérios de aceitação
- [x] Tela igual ao protótipo
- [x] Editar o nome de um ficheiro e salvar corretamente
- [x] Não alterar o conteúdo do ficheiro
