### ISSUE TITLE
US10 - Eu, enquanto usuário, desejo modificar meu perfil afim de personaliza-lo

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#11]
## Descrição da Issue
Desenvolvimento da funcionalidade de edição de perfil.

### Tasks: 

- [ ] Após estar logado, ser possível alterar nome de usuário e senha
- [ ] Ser possível adicionar sua data de aniversário e uma descrição sobre o usuário
- [ ] Criar tela
- [ ] Fazer a lógica de edição de usuário
- [ ] Conectar front-end com back-end

### Critérios de aceitação
- [ ] Tela igual ao protótipo de alta fidelidade
- [ ] Editar nome de usuário e senha e salvar alterações
