### ISSUE TITLE
US11 - Eu, enquanto usuário, desejo deletar deletar meus ficheiros para que eu possa encerrar a utilidade daquelas fichas

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#12]
## Descrição da Issue
Desenvolvimento da funcionalidade de deletar ficheiro.

### Tasks: 

- [x] Criar modal para deletar o ficheiro;
- [x] Criar lógica para deletar o ficheiro;
- [x] Integrar back-end e front-end;

### Critérios de aceitação
- [x] Deletar um ficheiro e seu conteúdo
- [x] Ser notificado que foi excluído com sucesso
