### ISSUE TITLE
US13 - Eu enquanto usuário desejo ver quais fichas foram criadas dentro do ficheiro afim de vizualiza-las

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#14]
## Descrição da Issue
Desenvolvimento da funcionalidade de vizualizar fichas

### Tasks: 

- [x] fazer tela para visualizar todas as fichas
- [x] fazer tela para visualizar as informações de uma fichas

### Critérios de aceitação
- [x] Tela igual ao protótipo
- [x] Visualização de todas as fichas criadas no ficheiro
- [x] Visualização de uma ficha
