### ISSUE TITLE
US17 - Eu, enquanto usuário, desejo ver quais ficheiros foram criadas dentro da minha conta para que eu possa visualiza-lo

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#18]
## Descrição da Issue
Desenvolvimento da funcionalidade de visualizar ficheiros.

### Tasks: 

- [x] Criar tela de visualização de fichas;
- [x] Conectar front com back;

### Critérios de aceitação
- [x] Tela igual ao protótipo de alta fidelidade
- [x] Visualizar os ficheiros criados
