### ISSUE TITLE
US18 - Eu, enquanto usuário, desejo criar um ficheiros na minha conta para que eu possa armazenar minhas fichas

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#19]
## Descrição da Issue
Desenvolvimento da funcionalidade de criar ficheiro.

### Tasks: 

- [x] Criar tela de criação de ficheiro
- [x] Criar lógica de criação de ficheiro
- [x] Conectar front com back

### Critérios de aceitação
- [x] Tela igual ao protótipo de alta fidelidade
- [x] Ser notificado que um ficheiro foi criado
