### ISSUE TITLE
US01 - Eu, enquanto usuário, desejo me cadastrar na plataforma para poder acessar os recursos do site

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#2]
## Descrição da Issue
Desenvolvimento da funcionalidade de cadastro de usuário.

### Tasks: 

- [x] Criar tela de cadastro de usuário
- [x] Criar lógica de cadastro de usuário
- [x] Conectar front com o back

### Critérios de aceitação
- [x] Tela igual ao protótipo de alta fidelidade
- [x] Cadastrar um usuário usando um nome,senha e e-mail único
- [x] Informar se foi cadastrado com sucesso ou houve uma falha
