### ISSUE TITLE
US13 - Eu enquanto usuário desejo ver quais fichas foram criadas dentro do ficheiro afim de vizualiza-las

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#42]
## Descrição da Issue
Desenvolvimento da funcionalidade de vizualizar fichas

### Tasks: 

- [ ] fazer tela para visualizar todas as fichas
- [ ] fazer tela para visualizar as informações de uma fichas

### Critérios de aceitação
- [ ] Tela igual ao protótipo
- [ ] Visualização de todas as fichas criadas no ficheiro
- [ ] Visualização de uma ficha
