### ISSUE TITLE
US04 - Eu, enquanto usuário, desejo acessar a plataforma usando a conta criada afim de começar a usar o site

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#5]
## Descrição da Issue
Desenvolvimento da funcionalidade de acessar conta.

### Tasks: 

- [x] Criar tela de login de usuário
- [x] Criar lógica de login
- [x] Conectar front com o back

### Critérios de aceitação
- [x]  Ser possível logar utilizando nome de usuário e senha
- [x]  Tela igual ao protótipo de alta fidelidade
- [x]  Retornar mensagem de confirmação ou erro
