### ISSUE TITLE
US15 - Eu, enquanto usuário, desejo modificar fichas existentes no meu ficheiro e as que possuo acesso afim de atualiza-las

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#6]
## Descrição da Issue
Desenvolvimento da funcionalidade de editar fichas.

### Tasks: 

- [x] Fazer logica para editar uma ficha
- [ ] ;
- [ ] ;

### Critérios de aceitação
- [ ] Tela igual ao protótipo
- [ ] Editar uma ficha e ao final salvar
