### ISSUE TITLE
US06 - Eu, enquanto usuário, desejo ver quais fichas foram criadas dentro do ficheiro afim de visualiza-las

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#7]
## Descrição da Issue
Desenvolvimento da funcionalidade de visualizar todas as fichas e os detalhes de uma.

### Tasks: 

- [x] ;
- [x] ;
- [x] ;

### Critérios de aceitação
- [x] Tela igual ao protótipo
- [x] Visualização de todas as fichas criadas no ficheiro
- [x] Visualização de uma ficha
