### ISSUE TITLE
US08 - Eu, enquanto usuário, desejo criar novas fichas no meu ficheiro para que eu possa participar da aventura de rpg

### ISSUE THREAD

**Issue by gabrielfreitass1** [FGAUnB-REQ-GM/2021.2-Tatsu#9]
## Descrição da Issue
Desenvolvimento da funcionalidade de criação de fichas.

### Tasks: 

- [x] Criar tela de criação de fichas
- [x] Criar lógica de criação de fichas
- [x] Conectar front com back

### Critérios de aceitação
- [x] Tela seguindo protótipo de alta fidelidade
- [x] Ser possível criar uma ficha dentro de um ficheiro corretamente
